### ISSUE TITLE
[Investigation / Brainstorming] - Additional Event Information

### ISSUE THREAD

**Issue by SamratSahoo** [GTBitsOfGood/bog-analytics#30]
## Overview

We are starting to run out of things to do for the dashboard so I need someone (you!) to be the acting product manager this sprint to help us brainstorm work for Sprints 4 and 5. You'll do a bit of research on other types of events or information we want to collect and then write up a short "report" (really just a paragraph or two) on what you found.

## Acceptance Criteria

- [x] Look into what other types of events we might want to collect (i.e., we currently have click, visit, and input events but look at different websites or frameworks and see what other types of interactions we can log - for example, one I can think of off the top of my head would maybe be an ActivityEvent where we log things like time spent on web page, etc.)
- [x] Look into what other information we might want to log in our [event interfaces](https://github.com/GTBitsOfGood/bog-analytics/?tab=readme-ov-file#event-interfaces)- a good place to start might be looking at what other frameworks log (i.e., see what Amplitude Analytics, Google Analytics, etc. logs)
- [ ] Write up a short product feature spec on:
    - [ ] What new types of events we want to log
    - [ ] What information we want to gather for each new type of event
    - [ ] What other information we might want to keep track of in pre-existing events

## Notes
You can write this up on a google doc, directly here on Github, or on Notion

**Comment by mgolla1623** [comment]
New Types of Events to Log:
1. ActivityEvent: This event will capture user engagement metrics such as time spent on a web page, scroll depth, and session duration. These metrics will provide insights into user behavior and help optimize the user experience.
  
2. FormSubmissionEvent: This event will track when a user submits a form on the website. It will include details such as form ID, fields submitted, and submission timestamp. Understanding form submission patterns can aid in optimizing form layouts and improving conversion rates.

 Information to Gather for Each New Type of Event:
1. ActivityEvent:
   - Time spent on page (in seconds)
   - Scroll depth (percentage scrolled)
   - Session duration (start and end timestamps)

2. FormSubmissionEvent:
   - Form ID or name
   - Field values submitted
   - Submission timestamp
  

Additional Information for Pre-existing Events:
1. Click Events:
   - Enhance with metadata such as button or link labels
   - Include timestamp of the click event
  
2. Visit Events:
   - Capture referral source (e.g., direct, organic search, referral)
   - Record landing page URL
  
3. Input Events:
   - Extend to include input field type (e.g., text, dropdown, checkbox)
   - Store timestamp of input event


This aims to deepen our understanding of user interactions and behaviors on the website, to make data-driven decisions to enhance the user experience and drive better outcomes.
