### ISSUE TITLE
[PMT] - Event Deletion Policy

### ISSUE THREAD

**Issue by SamratSahoo** [GTBitsOfGood/bog-analytics#80]
### Overview

Help - our database is starting to grow super big in size 😢 

![image](https://github.com/user-attachments/assets/056e7f23-6533-4a69-aea9-3798fc2e9291)

We need to implement a cron job that will delete base and custom events for each project based on their deletion policy

### Acceptance Criteria
- [ ] Create a subfolder in the root folder called `deletion-policy`
- [ ] Write a script that will delete all events that are older than the specified deletion policy for each project (based on createdAt date + deletionPolicy attribute)
    - [ ] Delete from the baseevents collection
    - [ ] Delete from the customevents collection
    - [ ] deletionPolicy values of 0 or lower equate to never deleting events in the project
    - [ ] Do not import methods/schemas, etc. from other folders - instead copy over any methods you need into separate file(s) into the `deletion-policy` folder (i.e., copy over the `dbConnect()` method into a new file as opposed to importing it from the `api` folder.
        - [ ] If you need certain types, you can install bog-analytics package and import the types from the package
        - [ ] We want to keep the code for each folder decoupled from one another (so we can run each part independently if needed) 
- [ ] Write a Dockerfile that will run this script
    - [ ] See [this Dockerfile](https://github.com/GTBitsOfGood/bog-analytics/blob/main/probe-action/Dockerfile) as a reference
- [ ]  Write a github actions workflow (`./.github/workflows/deletion-policy.yml`) that will run this docker container once a day
    - [ ] See [this workflow](https://github.com/GTBitsOfGood/bog-analytics/blob/main/.github/workflows/keep-alive.yml) as a reference 
    - [ ] See this accompanying [yaml file](https://github.com/GTBitsOfGood/bog-analytics/blob/main/probe-action/action.yml) for the github actions workflow

### Testing
- **Step 1:** Run the docker container for this project using `docker compose -f docker-compose.yml up`
- **Step 2:** Run the seed script for this project using `docker compose up -f docker-compose-seed.yml up`
- **Step 3:** Connect to the local database using MongoDB compass -- the database URL should be `127.0.0.1:27017`
- **Step 4:** Change the createdAt dates for some events to be older than a project's deletion policy
- **Step 5:** Run your script via the docker container and check if the events with the changed dates get deleted

### Notes
- Might be useful to see how to use docker + GH actions: https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action
- Let me know if you have any questions 🐱 <3

**Comment by jaynagpaul** [comment]
samrat help

**Comment by jaynagpaul** [comment]
nvm it doesnt work
